server:
  port: ${port:8099}

spring:
  datasource:                                     # 数据源的相关配置
    type: com.zaxxer.hikari.HikariDataSource      # 数据源的类型，可以更改为其他的数据源配置，比如druid
    driver-class-name: com.mysql.cj.jdbc.Driver     # mysql/MariaDB 的数据库驱动类名称
    url: jdbc:mysql://localhost:3306/imooc-red-book-dev?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 1234
    hikari:
      connection-timeout: 30000               # 等待连接池分配连接的最大时间（毫秒），超过这个时长还没有可用的连接，则会抛出SQLException
      minimum-idle: 5                         # 最小连接数
      maximum-pool-size: 20                   # 最大连接数
      auto-commit: true                       # 自动提交
      idle-timeout: 600000                    # 连接超时的最大时长（毫秒），超时则会被释放（retired）
      pool-name: DataSourceHikariCP           # 连接池的名字
      max-lifetime: 18000000                  # 连接池的最大生命时长（毫秒），超时则会被释放（retired）
      connection-test-query: SELECT 1
    redis:
      host: 192.168.153.129
      port: 6379
      database: 0
      password: 123456
  data:
    mongodb:
      uri: mongodb://root:123456@47.120.6.26:27017
      database: jjl-book
  rabbitmq:
    host: 47.120.6.26
    port: 5672
    username: admin
    password: admin
    virtual-host: jjl-red-book
  application:
    name: jjl-red-book-nacos
  cloud:
    nacos:
      discovery:
        server-addr: 47.120.6.26:8848

management:
  endpoint:
    web:
      exposure:
        include: "*"

#minio配置
minio:
  endpoint: http://47.120.6.26:9000
  fileHost: http://47.120.6.26:9000
  bucketName: jjl
  accessKey: username
  secretKey: password
  imgSize: 1024
  fileSize: 1024


